### PR TITLE
Xenial   webengine5 14 pr

### LINKED ISSUE #21: Text selection (like in the old browser ?)
Would it be possible to have a text selection like with the Oxide based browser with the browser-ng based on QtWebEngine ?
textselection

I've thought about several possibilities, but have not yet come to a conclusion.

What I already do know: the [ContextMenuRequest](https://doc.qt.io/qt-5/qml-qtwebengine-contextmenurequest.html) contains the x and y coordinate of the control the event was sent from.
And it is possible to get the corresponding DOM element via [JavaScript.](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint)

https://github.com/component/textarea-caret-position/blob/master/index.js allows to calculate the coordinates of the caret, the selection start, and selection end. 

So I see the following possibilities:
1) draw QML rectangles for the selection, and update their position with the text selection, if the users moves them, adapt the text selection via JavaScript. This needs to take into account the browser scrolling position, zoom and that not all of the text might be visible
2) in an "select mode" just let the user select the text (like for example in the terminal app) without the rectangles
3) In "select mode" the content of the control is copied to a QML TextAera, the user can select the text there, and later it is copied back to the original control
4) Make a feature request to QtWebEngine, that a future version supports configurable touch selection control (like Oxide)

I'm not really sure we can provide the same user experience without controlling the backend (oxide) here. E.g. at least 1) feels to be a very "fragile" implementation, because you are not really bound to the text, but rather to coordinates here...

### LINKED ISSUE #223: User-Agent Chromium Version outdated
The chromium version on UBports is outdate. I hove ubports team will change user agent on browser to use message on facebook.com (link window phone).

### PR DESCRIPTION
**Pull request by balcy**
fixes https://github.com/ubports/morph-browser/issues/21
fixes https://github.com/ubports/morph-browser/issues/223

### CODE REVIEW

**Comment by balcy** [comment]
oops that was a bit too early, I've just seen 
https://github.com/qt/qtwebengine/commit/323e09ded5d6c2726227afa937df44060c0cc341
but the release of QtWebEngine 5.14.2 is scheduled for March 17th:
https://wiki.qt.io/Qt_5.14_Release

**Comment by balcy** [comment]
There is still a bit of delay with the 5.14.2 release of Qt: https://bugreports.qt.io/browse/QTBUG-82061
switched back to 5.14.1 for now.

**Comment by balcy** [comment]
morph adaption: https://github.com/ubports/morph-browser/pull/307

**Comment by nanu-c** [comment]
Hopefully this gets merged soon, because we have a nasty bug in axolotl with scrolling wich isn't there in recent chromium/firefox but in the webkit that is on the ut

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
The system settings Online Accounts plugins which use the WebEngine (Google and Evernote) must be adapted to QtWebEngine 5.14 before this can be merged. Currently, trying to add one of these accounts results in the webpage simply closing.

**Comment by balcy** [comment]
This is because of the "No suitable graphics backend found" error (https://github.com/ubports/qtwebengine-opensource-src-packaging/issues/32)
Would it be an option to include `QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"` globally (e.g. in `/etc/environment`) on devices that do not support QtWebEngine with GPU ?
That would avoid apps using QtWebEngine directly (not via webapp-container) to add it for each app. (after adding it to `/etc/environment` and rebooting the device, the UI for the google online account did appear for me)

**Comment by peat-psuwit** [comment]
Seems like the `qtwebengine-no-gpu.patch`, which adds `QT_WEBENGINE_DISABLE_GPU`, is removed. `QT_WEBENGINE_DISABLE_GPU` is added in `lxc-android-config` as a `profile.d` drop-in; I'll update it to use the new env.

**Comment by peat-psuwit** [comment]
With (essentially) ubports/lxc-android-config#34, the Google and Evernote account adding pages seem to be loaded successfully.

Well, except that Google still blocks embedded browsers from logging in. But I guess that's a known issue.

**Comment by balcy** [comment]
there is one thing that does worry me: on my phone from time to time morph "hangs" (page stuck) and I don't know the reason yet. It might be a memory issue on my phone, but it could be another segfault of QtWebengine that is not fixed yet.

**Comment by peat-psuwit** [comment]
Another side-effect of upgrading to QWE 5.14: the selection menu seems to be handled (partially) by Chromium/QWE now. When selecting something, a small menu with "Copy" and "…" buttons will appear. Our menu appears after pressing the "…" (and it looks a bit offset?).

| Initial menu | After pressing "…" |
---------------|----------------------
|screenshot20200710_031835400|screenshot20200710_031841378|

**Comment by balcy** [comment]
actually one of the main motivations for the upgrade :) 
[the text selection handles, that is]
You're right the menu seems a bit offset, it should get the coordinates of the context menu request. There are the 'fitsAbove' / 'fitsBelow' logic taken from webbrowser app, maybe this needs to be improved. Ideally our menu should be displayed close to the point (above or below) where the user opened the context menu, and follow the scroll. In certain conditions it will be displayed centered.

**Comment by UniversalSuperBox** [comment]
I believe this is something that can be fixed after merge, the question is, is there anything still blocking this merge?

Does the random `Illegal Instruction` tab freeze still occur?

**Comment by balcy** [comment]
For me it has not reappeared yet, I was hoping to see it in gdb...
I don't know of another blocking issue, but I have only tested it on BQ Aquaris 4.5

**Review by UniversalSuperBox — APPROVED** [review]
It has not reappeared for me either. Even with extreme tab switching, it stays up.

Ready for merge with https://github.com/ubports/morph-browser/pull/328

**Comment by Fuseteam** [comment]
while there's two menu's now and the first menu is white even under surudark, it is not white on white and the text handles just works
gitlab seems to load very slow but unsure if that's due to the upgrade and logging into gitlab works

**Comment by jezek** [comment]
There is a call for testing, how exactly test this?

**Comment by UniversalSuperBox** [comment]
We've been putting QWE 5.14 through the wringer over the past few weeks to find any critical issues. Past the fixed https://github.com/ubports/qtwebengine-opensource-src-packaging/issues/38, none have been found.

**Comment by Flaburgan** [comment]
I had two crashes of Morph this morning, but I find nothing in the logs (`.cache/upstart/application-legacy-morph-browser-.log` and `unity8.log`) am I looking at the right places? The logs aren't very verbose and not timestamped, making them hard to grep

**Comment by peat-psuwit** [comment]
@Flaburgan What device you're using and which image version, please?

**Comment by Flaburgan** [comment]
Sorry, I'm using a Fairphone 2 with the new camera module, Halium 5.1 port, running the last release candidate (v86 released the 9th of September). One of the crash occurred when I was answering a post on the UBPorts forum and rotated the device, but I can't reproduce it.

**Pull request merged**
